name: Auto Generate Sitemap

on:
  push:
    branches:
      - main
    paths:
      - "**/*.html"

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate Sitemap
      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in $(find . -name "*.html" ! -path "./node_modules/*" ! -path "./.github/*"); do

            clean_path=$(echo "$file" | sed 's|^\./||')

            last_commit=$(git log -1 --format="%cI" -- "$file")

            url="https://extramilesenergy.in/$clean_path"

            echo "  <url>" >> sitemap.xml
            echo "    <loc>$url</loc>" >> sitemap.xml
            echo "    <lastmod>$last_commit</lastmod>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml

          done

          echo "</urlset>" >> sitemap.xml

      # Upload Sitemap (NO PUSH = NO ERROR)
      - name: Upload Sitemap
        uses: actions/upload-artifact@v4
        with:
          name: sitemap
          path: sitemap.xml
